import os
import json
import logging
from src.pipeline.tag_generator import tag_generator
from src.services.image_service import image_service

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("test_real_tag_generation")

def main():
    img_path = os.path.abspath("test_files/beauty_1755438760705.jpeg")
    video_path = os.path.abspath("test_files/IMG_2514.MOV")

    # Real VLM descriptions generated by Qwen3-VL-8B
    img_vlm_desc = (
        "这是一张从车内一个独特的、略微倾斜的视角拍摄，营造出一种私密、自拍的氛围。"
        "主体人物：一位年轻女性，正坐在驾驶座或副驾驶座上。她用左手轻轻捂住自己的左半边脸，"
        "只露出右眼和嘴角，眼神直视着前方的后视镜，表情显得俏皮、害羞或略带疲惫。"
        "外貌与穿着：她有着深色头发，身穿粉色上衣，头发上别着一个显眼的粉色发饰..."
    )

    vid_vlm_desc = (
        "画面中心是两颗被打开的生蚝，它们被放置在一个容器中，可能是一个塑料袋或泡沫盒。"
        "上方的生蚝：这颗生蚝的壳已经完全打开，露出了内部饱满的蚝肉。"
        "蚝肉呈淡黄色至灰白色，质地看起来非常新鲜、湿润且富有弹性，表面泛着自然的光泽。"
        "蚝肉的形态自然卷曲，部分边缘带有半透明的质感，显示出其新鲜度..."
    )

    print("==================================================", flush=True)
    print("真实大模型描述文本 -> 6 大维度体系标签抽取测试", flush=True)
    print("==================================================", flush=True)

    # 1. Image Tags Test
    print(f"\n--- [1] 真实图片 [{os.path.basename(img_path)}] 标签提取实测 ---", flush=True)
    colors = image_service.extract_dominant_colors(img_path)
    img_cat_tags = tag_generator.generate_categorized_tags(img_vlm_desc)
    img_flat_tags = tag_generator.flatten_tags(img_vlm_desc)
    img_flat_tags.extend([f"主色_{c}" for c in colors[:2]])

    print(f"► Hex 提取图片主色调: {colors}", flush=True)
    print(f"► 6 大维度结构化分类标签:\n{json.dumps(img_cat_tags, ensure_ascii=False, indent=2)}", flush=True)
    print(f"► 展平去重最终全量标签集 ({len(img_flat_tags)}个):", flush=True)
    print(img_flat_tags, flush=True)

    # 2. Video Keyframe Tags Test
    print(f"\n--- [2] 真实视频关键帧 [{os.path.basename(video_path)}] 标签提取实测 ---", flush=True)
    vid_cat_tags = tag_generator.generate_categorized_tags(vid_vlm_desc)
    vid_flat_tags = tag_generator.flatten_tags(vid_vlm_desc)

    print(f"► 6 大维度结构化分类标签:\n{json.dumps(vid_cat_tags, ensure_ascii=False, indent=2)}", flush=True)
    print(f"► 展平去重最终全量标签集 ({len(vid_flat_tags)}个):", flush=True)
    print(vid_flat_tags, flush=True)

    print("\n==================================================", flush=True)
    print("6 大维度体系标签抽取能力测试全部成功通过！", flush=True)

if __name__ == "__main__":
    main()
